/* Sistema multilingua dell'interfaccia (IT/EN/ES). Le ricette e i piatti tipici restano solo in
   italiano: qui si traduce solo il "chrome" dell'app (nav, titoli, pulsanti, etichette, filtri). */

const LANG_KEY = "appLanguage";
const SUPPORTED_LANGS = ["it", "en", "es"];

const I18N = {
  it: {
    nav: { home: "Home", menu: "Menu", ricette: "Ricette", scopri: "Scopri", spesa: "Spesa", storico: "Storico", calorie: "Calorie", guida: "Guida" },
    common: {
      footerNote: "I dati sono salvati solo su questo dispositivo/browser.",
      resetAll: "Cancella tutti i dati",
      add: "+ Aggiungi",
      clear: "Cancella"
    },
    days: {
      lunedi: "Lunedì", martedi: "Martedì", mercoledi: "Mercoledì",
      giovedi: "Giovedì", venerdi: "Venerdì", sabato: "Sabato", domenica: "Domenica"
    },
    meals: { colazione: "Colazione", pranzo: "Pranzo", cena: "Cena", spuntini: "Spuntini" },
    categorie: { colazione: "Colazione", pranzo: "Pranzo", cena: "Cena", spuntino: "Spuntino" },
    stili: { leggero: "Leggero", bilanciato: "Bilanciato", goloso: "Goloso" },
    tempi: { veloce: "Veloce", elaborato: "Più elaborata" },
    budgetCategorie: { cibo: "Cibo", altri: "Altri articoli", consegna: "Consegne a domicilio", fuori: "Cene fuori" },
    allergeni: { glutine: "Glutine", lattosio: "Lattosio", frutta_guscio: "Frutta a guscio", uova: "Uova" },
    home: {
      title: "Sfamati",
      subtitle: "Il tuo kit di sopravvivenza per la vita da Erasmus: cosa mangiare, cosa comprare e quanto spendi, tutto in un posto solo",
      howItWorks: "Perché questa app",
      intro1: "Sfamati nasce per una cosa semplice: toglierti la fatica di decidere ogni giorno cosa mangiare, cosa comprare e quanto stai spendendo, proprio nel periodo in cui hai già cento altre cose nuove a cui pensare.",
      intro2: "Ricette pronte, lista della spesa automatica, budget sotto controllo, piatti tipici da scoprire, divisione delle spese con i coinquilini e uno storico di cosa hai mangiato: tutto gratuito, senza account e senza pubblicità.",
      intro3: "I tuoi dati restano solo sul tuo dispositivo: nessuna registrazione richiesta.",
      guidaCta: "📖 Guida completa a tutte le funzioni",
      dishOfDay: "🍽️ Piatto consigliato di oggi",
      navMenuTitle: "Menu Settimanale",
      navMenuDesc: "Scegli cosa mangiare ogni giorno, tra ricette pronte e alimenti liberi",
      navRicetteTitle: "Ricette",
      navRicetteDesc: "Oltre 1900 piatti facili, con filtri per pesce, stile e tempo di preparazione",
      navScopriTitle: "Scopri",
      navScopriDesc: "I piatti tipici del paese dove vivi il tuo Erasmus, per assaggiare la cultura locale",
      navSpesaTitle: "Lista della Spesa",
      navSpesaDesc: "Generata dal tuo menu, con budget settimanale o mensile, divisione spese con i coinquilini e grafico delle spese",
      navCalorieTitle: "Calorie",
      navCalorieDesc: "Facoltativo: un riepilogo solo per chi sceglie di attivarlo",
      navStoricoTitle: "Storico",
      navStoricoDesc: "Rivedi cosa hai mangiato nelle settimane precedenti",
      addToMenu: "Aggiungilo al tuo menu",
      statsTitle: "📊 Le tue statistiche",
      statsEmpty: "Inizia a usare l'app — menu, ricette, spesa — e qui vedrai un riepilogo di quello che hai fatto.",
      statsUniqueRecipes: "ricette diverse provate",
      statsFavorites: "ricette preferite",
      statsWeeks: "settimane monitorate",
      statsPhotos: "foto ricordo",
      statsDeliveries: "ordini delivery",
      statsEatingOut: "cene fuori",
      statsTotalSpent: "spesa totale",
      statsTopDish: "Il tuo piatto più cucinato:",
      statsTopStyle: "Il tuo stile preferito:"
    },
    menu: {
      title: "Il Mio Menu Settimanale",
      subtitle: "Scegli cosa mangiare giorno per giorno, tra ricette pronte e alimenti liberi",
      viewHistory: "📚 Vedi settimane precedenti",
      autoGenerateSummary: "🎲 Genera menu automatico",
      autoGenNoFish: "Escludi piatti a base di pesce",
      autoGenQuick: "Solo ricette veloci",
      autoGenOverwrite: "Sostituisci anche i pasti già inseriti",
      autoGenAllergeniLabel: "Escludi se hai allergie/intolleranze a:",
      autoGenEvitaLabel: "Altri alimenti da evitare",
      autoGenEvitaPlaceholder: "Es. funghi, olive, piccante... (separati da virgola)",
      autoGenModalitaLabel: "Modalità",
      modeMisto: "🎯 Misto (bilanciato)",
      modeFitness: "💪 Fitness (leggero, meno calorie)",
      modeVeloce: "⚡ Veloce (solo ricette rapide)",
      modeGoloso: "🍰 Goloso (comfort food)",
      autoGenerateBtn: "Genera menu della settimana",
      autoGenerateDone: "✅ Fatto! {n} pasti aggiunti.",
      autoGenerateNothing: "Nessun pasto aggiunto: prova a togliere qualche filtro o attiva la sostituzione.",
      fixedMealsSummary: "📌 Pasti fissi per tutta la settimana",
      fixedMealsIntro: "Se mangi sempre la stessa cosa a colazione (o a un altro pasto), fissala qui una volta sola: si applica automaticamente a tutti i 7 giorni, e continuerà a farlo anche nelle settimane future finché non la cambi o la rimuovi. Puoi sempre modificare un singolo giorno senza toccare gli altri, e la generazione automatica non tocca i pasti fissati.",
      fixedMealsRecipeLabel: "Cerca una ricetta",
      fixedMealsFoodAlt: "Oppure un alimento libero",
      fixedMealsFixBtn: "📌 Fissa per tutta la settimana",
      fixedMealsRemoveBtn: "✕ Rimuovi",
      fixedMealsCurrent: "Fissato: {nome}",
      fixedMealsNone: "Non fissato"
    },
    ricette: {
      title: "Ricette Consigliate",
      subtitle: "Oltre 1900 piatti facili per la vita da Erasmus, tra carne, pesce e opzioni vegetariane",
      searchPlaceholder: "🔍 Cerca una ricetta per nome o ingrediente...",
      filterAll: "Tutte",
      filterAllStyles: "Tutti gli stili",
      filterAllTimes: "Tutte le ricette",
      filterElaborate: "Più elaborate",
      filterFishAll: "🐟 Pesce: tutte",
      filterFishExclude: "Escludi pesce",
      filterFishOnly: "Solo pesce",
      allergeneLabel: "Escludi se sei allergico/intollerante a:",
      allergeneDisclaimer: "⚠️ Attenzione: questo filtro è puramente indicativo e si basa solo sugli ingredienti elencati nella ricetta, che potrebbero essere incompleti o non riflettere possibili contaminazioni incrociate. L'app non fornisce consulenza medica: se hai un'allergia o un'intolleranza, verifica sempre gli ingredienti reali prima di mangiare e consulta un medico in caso di dubbi.",
      frigoSummary: "🧊 Cosa hai in frigo? Trova ricette con quello che hai già",
      frigoPlaceholder: "Es. zucchine, uova, pomodori... (separati da virgola)",
      frigoFind: "Trova ricette",
      loadMore: "Mostra altre ricette",
      filterFavorites: "⭐ Solo preferite",
      filterQuickMode: "⚡ Sono di corsa"
    },
    scopri: {
      title: "Scopri i Piatti Tipici",
      subtitle: "Cosa si mangia nella tua città Erasmus (o in quella dei tuoi sogni)",
      searchPlaceholder: "🔍 Cerca un piatto o un paese...",
      filterAll: "🌍 Tutti i paesi"
    },
    spesa: {
      title: "Lista della Spesa",
      subtitle: "Generata automaticamente dal tuo menu settimanale",
      refresh: "Aggiorna dal menu",
      clearChecked: "Deseleziona tutto",
      fromMenu: "Dal menu settimanale",
      emptyShopping: "Non hai ancora selezionato ricette o alimenti nel Menu Settimanale.",
      otherItems: "Altri articoli",
      extraNamePlaceholder: "Es. detersivo, carta igienica...",
      extraQtyPlaceholder: "Quantità (facoltativa)",
      budgetTitle: "💶 Budget cibo",
      thisWeek: "Questa settimana",
      thisMonth: "Questo mese",
      totalSpent: "Totale speso",
      amountPlaceholder: "Importo €",
      notePlaceholder: "Nota (es. supermercato)",
      shared: "Spesa condivisa con i coinquilini",
      registerExpense: "+ Registra spesa",
      roommatesTitle: "👥 Coinquilini",
      roommatesHint: "Aggiungi chi vive con te per dividere le spese condivise in modo equo.",
      roommateNamePlaceholder: "Nome coinquilino",
      settlementTitle: "🤝 Chi deve cosa",
      settlementHint: "Calcolato sulle spese condivise registrate nel periodo selezionato sopra (settimana o mese).",
      currencyTitle: "💱 Convertitore Valuta",
      currencyHint: "Imposta la valuta locale e il tasso di cambio per convertire al volo i tuoi importi.",
      currencyRateLabel: "1 € =",
      currencyRefresh: "Aggiorna tasso",
      currencyUpdating: "Aggiornamento in corso...",
      currencyUpdated: "Tasso aggiornato.",
      currencyUpdateFailed: "Impossibile aggiornare automaticamente: usa il tasso manuale."
    },
    storico: {
      title: "Storico Settimanale",
      subtitle: "Rivedi cosa hai mangiato nelle settimane precedenti",
      empty: "Non ci sono ancora settimane archiviate: torneranno visibili qui non appena inizierai una nuova settimana nel Menu.",
      noFood: "Nessun alimento inserito.",
      delivery: "consegna",
      eatingOut: "fuori casa"
    },
    calorie: {
      title: "Riepilogo Calorie",
      subtitle: "Una sezione facoltativa: la vedi solo se scegli tu di attivarla",
      consentTitle: "Vuoi tenere traccia delle calorie?",
      consentText: "È una funzione facoltativa. Alcune persone la trovano utile, altre preferiscono non pensare ai numeri: va benissimo in entrambi i casi.",
      consentYes: "Sì, mostrami il riepilogo",
      consentNo: "No, preferisco di no",
      declinedTitle: "Nessun numero da vedere qui",
      declinedText: "Hai scelto di non tenere traccia delle calorie. Puoi cambiare idea in qualsiasi momento.",
      changeMind: "Cambia preferenza",
      dailyGoal: "Obiettivo giornaliero",
      hideAgain: "Nascondi di nuovo questa sezione"
    },
    guida: {
      title: "Guida a Sfamati",
      subtitle: "Tutto quello che c'è da sapere per usare l'app al meglio",
      backHome: "← Torna alla Home",
      sectionMenuTitle: "📅 Menu Settimanale",
      sectionMenuText: "Per ogni giorno scegli cosa mangiare a colazione, pranzo, cena e spuntini: cerca tra le ricette pronte oppure aggiungi un alimento libero scrivendolo a mano. Se sei uscito a mangiare fuori o hai ordinato da asporto, segnalo con gli appositi pulsanti così viene conteggiato anche nel budget. Con \"Genera menu automatico\" riempi l'intera settimana in un clic, scegliendo tra modalità Misto, Fitness (leggero e meno calorie), Veloce (solo ricette rapide) o Goloso (comfort food), escludendo il pesce e le tue allergie/intolleranze (glutine, lattosio, frutta a guscio, uova) o qualsiasi altro alimento tu voglia evitare.",
      sectionRicetteTitle: "🍝 Ricette",
      sectionRicetteText: "Oltre 1900 ricette filtrabili per categoria, stile (leggero, bilanciato, goloso), tempo di preparazione, presenza di pesce e allergeni da escludere. Salva le tue preferite con la stella, attiva la modalità \"Sono di corsa\" per vedere solo ricette veloci con pochi ingredienti, oppure scrivi cosa hai in frigo per trovare ricette con quello che hai già in casa.",
      sectionScopriTitle: "🌍 Scopri",
      sectionScopriText: "Una raccolta di piatti tipici di 15 paesi europei, per assaggiare la cultura locale del posto dove vivi il tuo Erasmus, o solo per curiosità. Filtra per paese o cerca un piatto specifico.",
      sectionSpesaTitle: "🛒 Lista della Spesa",
      sectionSpesaText: "Viene generata automaticamente dagli ingredienti del tuo Menu Settimanale: spunta quello che hai già comprato e aggiungi articoli extra non alimentari. Nella stessa pagina trovi anche il budget (spesa, consegne, cene fuori) diviso per settimana o mese, la divisione delle spese condivise con i coinquilini e un convertitore di valuta per chi vive fuori dall'area euro.",
      sectionStoricoTitle: "📚 Storico",
      sectionStoricoText: "Ogni volta che inizia una nuova settimana, quella precedente viene archiviata automaticamente qui: puoi rivedere cosa hai mangiato, con tanto di foto ricordo, fino a 26 settimane indietro.",
      sectionCalorieTitle: "🔥 Calorie",
      sectionCalorieText: "Una sezione facoltativa: resta nascosta finché non scegli tu di attivarla. Se la attivi, mostra un riepilogo delle calorie del menu e ti permette di impostare un obiettivo giornaliero. Puoi disattivarla in qualsiasi momento.",
      sectionDatiTitle: "🔒 I tuoi dati",
      sectionDatiText: "Tutto quello che inserisci — menu, ricette preferite, foto, spese, storico — resta salvato solo sul tuo telefono o computer, nel browser che stai usando. Non c'è nessun account, nessuna registrazione e nessun dato che lascia il tuo dispositivo. Il rovescio della medaglia: se cambi browser o dispositivo, o cancelli i dati di navigazione, perdi anche i tuoi dati salvati qui.",
      sectionLinguaTitle: "🌐 Lingua",
      sectionLinguaText: "Puoi cambiare la lingua dell'interfaccia in italiano, inglese o spagnolo con le bandierine in alto a destra in ogni pagina. Le ricette e i piatti tipici restano in italiano, ma tutto il resto dell'app si traduce.",
      sectionDisclaimerTitle: "⚠️ Disclaimer su allergie e salute",
      sectionDisclaimerText: "Le informazioni su ingredienti, allergeni e calorie presenti nell'app sono fornite a scopo puramente informativo e si basano sugli ingredienti indicati in ciascuna ricetta, che potrebbero essere incompleti, imprecisi o non tenere conto di contaminazioni incrociate durante la preparazione. L'app non fornisce consulenza medica, nutrizionale o dietetica di alcun tipo. Se soffri di allergie, intolleranze o altre condizioni di salute, verifica sempre personalmente gli ingredienti reali dei prodotti che acquisti e consulta un medico o uno specialista in caso di dubbi. L'uso dei filtri per allergeni è a tuo rischio e non deve essere considerato una garanzia di sicurezza alimentare."
    }
  },

  en: {
    nav: { home: "Home", menu: "Menu", ricette: "Recipes", scopri: "Discover", spesa: "Shopping", storico: "History", calorie: "Calories", guida: "Guide" },
    common: {
      footerNote: "Your data is only saved on this device/browser.",
      resetAll: "Clear all data",
      add: "+ Add",
      clear: "Clear"
    },
    days: {
      lunedi: "Monday", martedi: "Tuesday", mercoledi: "Wednesday",
      giovedi: "Thursday", venerdi: "Friday", sabato: "Saturday", domenica: "Sunday"
    },
    meals: { colazione: "Breakfast", pranzo: "Lunch", cena: "Dinner", spuntini: "Snacks" },
    categorie: { colazione: "Breakfast", pranzo: "Lunch", cena: "Dinner", spuntino: "Snack" },
    stili: { leggero: "Light", bilanciato: "Balanced", goloso: "Indulgent" },
    tempi: { veloce: "Quick", elaborato: "More elaborate" },
    budgetCategorie: { cibo: "Groceries", altri: "Other items", consegna: "Deliveries", fuori: "Eating out" },
    allergeni: { glutine: "Gluten", lattosio: "Lactose", frutta_guscio: "Tree nuts", uova: "Eggs" },
    home: {
      title: "Sfamati",
      subtitle: "Your survival kit for Erasmus life: what to eat, what to buy, and how much you spend — all in one place",
      howItWorks: "Why this app",
      intro1: "Sfamati exists for one simple reason: to take the daily hassle out of deciding what to eat, what to buy and how much you're spending, right when you already have a hundred other new things to figure out.",
      intro2: "Ready-made recipes, an automatic shopping list, budget under control, local dishes to discover, roommate expense splitting and a history of what you ate: all free, no account, no ads.",
      intro3: "Your data stays only on your device: no sign-up required.",
      guidaCta: "📖 Full guide to every feature",
      dishOfDay: "🍽️ Today's recommended dish",
      navMenuTitle: "Weekly Menu",
      navMenuDesc: "Choose what to eat every day, from ready-made recipes or free-form entries",
      navRicetteTitle: "Recipes",
      navRicetteDesc: "Over 1900 easy dishes, with filters for fish, style and prep time",
      navScopriTitle: "Discover",
      navScopriDesc: "Traditional dishes from the country where you're doing your Erasmus, to taste the local culture",
      navSpesaTitle: "Shopping List",
      navSpesaDesc: "Generated from your menu, with weekly or monthly budget, roommate expense splitting and spending chart",
      navCalorieTitle: "Calories",
      navCalorieDesc: "Optional: a summary only for those who choose to turn it on",
      navStoricoTitle: "History",
      navStoricoDesc: "Look back at what you ate in previous weeks",
      addToMenu: "Add it to your menu",
      statsTitle: "📊 Your stats",
      statsEmpty: "Start using the app — menu, recipes, shopping — and you'll see a recap of what you've done here.",
      statsUniqueRecipes: "different recipes tried",
      statsFavorites: "favourite recipes",
      statsWeeks: "weeks tracked",
      statsPhotos: "memory photos",
      statsDeliveries: "delivery orders",
      statsEatingOut: "times eating out",
      statsTotalSpent: "total spent",
      statsTopDish: "Your most-cooked dish:",
      statsTopStyle: "Your favourite style:"
    },
    menu: {
      title: "My Weekly Menu",
      subtitle: "Choose what to eat day by day, from ready-made recipes or free-form entries",
      viewHistory: "📚 See previous weeks",
      autoGenerateSummary: "🎲 Auto-generate menu",
      autoGenNoFish: "Exclude fish-based dishes",
      autoGenQuick: "Quick recipes only",
      autoGenOverwrite: "Also replace meals already added",
      autoGenAllergeniLabel: "Exclude if you're allergic/intolerant to:",
      autoGenEvitaLabel: "Other foods to avoid",
      autoGenEvitaPlaceholder: "E.g. mushrooms, olives, spicy... (comma separated)",
      autoGenModalitaLabel: "Mode",
      modeMisto: "🎯 Mixed (balanced)",
      modeFitness: "💪 Fitness (light, lower calories)",
      modeVeloce: "⚡ Quick (fast recipes only)",
      modeGoloso: "🍰 Indulgent (comfort food)",
      autoGenerateBtn: "Generate this week's menu",
      autoGenerateDone: "✅ Done! {n} meals added.",
      autoGenerateNothing: "No meals added: try removing a filter or turning on replacement.",
      fixedMealsSummary: "📌 Fixed meals for the whole week",
      fixedMealsIntro: "If you always eat the same thing for breakfast (or another meal), fix it here once: it's applied automatically to all 7 days, and will keep doing so in future weeks too until you change or remove it. You can always edit a single day without affecting the others, and auto-generate won't touch fixed meals.",
      fixedMealsRecipeLabel: "Search for a recipe",
      fixedMealsFoodAlt: "Or a free-text food",
      fixedMealsFixBtn: "📌 Fix for the whole week",
      fixedMealsRemoveBtn: "✕ Remove",
      fixedMealsCurrent: "Fixed: {nome}",
      fixedMealsNone: "Not fixed"
    },
    ricette: {
      title: "Recommended Recipes",
      subtitle: "Over 1900 easy dishes for Erasmus life, with meat, fish and vegetarian options",
      searchPlaceholder: "🔍 Search a recipe by name or ingredient...",
      filterAll: "All",
      filterAllStyles: "All styles",
      filterAllTimes: "All recipes",
      filterElaborate: "More elaborate",
      filterFishAll: "🐟 Fish: all",
      filterFishExclude: "Exclude fish",
      filterFishOnly: "Fish only",
      allergeneLabel: "Exclude if you're allergic/intolerant to:",
      allergeneDisclaimer: "⚠️ Warning: this filter is purely indicative and is based only on the ingredients listed in the recipe, which may be incomplete or may not reflect possible cross-contamination. The app does not provide medical advice: if you have an allergy or intolerance, always check the actual ingredients before eating and consult a doctor if in doubt.",
      frigoSummary: "🧊 What's in your fridge? Find recipes with what you already have",
      frigoPlaceholder: "E.g. zucchini, eggs, tomatoes... (comma separated)",
      frigoFind: "Find recipes",
      loadMore: "Show more recipes",
      filterFavorites: "⭐ Favourites only",
      filterQuickMode: "⚡ In a rush"
    },
    scopri: {
      title: "Discover Traditional Dishes",
      subtitle: "What people eat in your Erasmus city (or the one you dream of)",
      searchPlaceholder: "🔍 Search a dish or a country...",
      filterAll: "🌍 All countries"
    },
    spesa: {
      title: "Shopping List",
      subtitle: "Automatically generated from your weekly menu",
      refresh: "Refresh from menu",
      clearChecked: "Uncheck all",
      fromMenu: "From your weekly menu",
      emptyShopping: "You haven't selected any recipes or foods in the Weekly Menu yet.",
      otherItems: "Other items",
      extraNamePlaceholder: "E.g. detergent, toilet paper...",
      extraQtyPlaceholder: "Quantity (optional)",
      budgetTitle: "💶 Food budget",
      thisWeek: "This week",
      thisMonth: "This month",
      totalSpent: "Total spent",
      amountPlaceholder: "Amount €",
      notePlaceholder: "Note (e.g. supermarket)",
      shared: "Shared expense with roommates",
      registerExpense: "+ Log expense",
      roommatesTitle: "👥 Roommates",
      roommatesHint: "Add the people you live with to split shared expenses fairly.",
      roommateNamePlaceholder: "Roommate name",
      settlementTitle: "🤝 Who owes what",
      settlementHint: "Calculated from shared expenses logged in the period selected above (week or month).",
      currencyTitle: "💱 Currency Converter",
      currencyHint: "Set your local currency and exchange rate to convert amounts on the fly.",
      currencyRateLabel: "1 € =",
      currencyRefresh: "Refresh rate",
      currencyUpdating: "Updating...",
      currencyUpdated: "Rate updated.",
      currencyUpdateFailed: "Couldn't update automatically: use the manual rate."
    },
    storico: {
      title: "Weekly History",
      subtitle: "Look back at what you ate in previous weeks",
      empty: "No archived weeks yet: they'll show up here as soon as a new week starts in the Menu.",
      noFood: "No food added.",
      delivery: "delivery",
      eatingOut: "eating out"
    },
    calorie: {
      title: "Calorie Summary",
      subtitle: "An optional section: you'll only see it if you choose to turn it on",
      consentTitle: "Do you want to track calories?",
      consentText: "This is an optional feature. Some people find it useful, others prefer not to think about the numbers: either way is totally fine.",
      consentYes: "Yes, show me the summary",
      consentNo: "No, I'd rather not",
      declinedTitle: "No numbers to see here",
      declinedText: "You chose not to track calories. You can change your mind at any time.",
      changeMind: "Change preference",
      dailyGoal: "Daily goal",
      hideAgain: "Hide this section again"
    },
    guida: {
      title: "Guide to Sfamati",
      subtitle: "Everything you need to know to get the most out of the app",
      backHome: "← Back to Home",
      sectionMenuTitle: "📅 Weekly Menu",
      sectionMenuText: "For each day choose what to eat for breakfast, lunch, dinner and snacks: search among the ready-made recipes or add a free-form food by typing it in. If you ate out or ordered takeaway, log it with the dedicated buttons so it's counted in your budget too. With \"Auto-generate menu\" you can fill the whole week in one click, choosing between Mixed, Fitness (light, lower calories), Quick (fast recipes only) or Indulgent (comfort food) mode, excluding fish and your allergies/intolerances (gluten, lactose, tree nuts, eggs), or any other food you want to avoid.",
      sectionRicetteTitle: "🍝 Recipes",
      sectionRicetteText: "Over 1900 recipes filterable by category, style (light, balanced, indulgent), prep time, whether they contain fish, and allergens to exclude. Save your favourites with the star, turn on \"In a rush\" mode to see only quick recipes with few ingredients, or type what's in your fridge to find recipes using what you already have.",
      sectionScopriTitle: "🌍 Discover",
      sectionScopriText: "A collection of traditional dishes from 15 European countries, to taste the local culture of the place where you're doing your Erasmus, or just out of curiosity. Filter by country or search for a specific dish.",
      sectionSpesaTitle: "🛒 Shopping List",
      sectionSpesaText: "Automatically generated from the ingredients in your Weekly Menu: check off what you've already bought and add extra non-food items. On the same page you'll also find your budget (groceries, deliveries, eating out) broken down by week or month, roommate expense splitting, and a currency converter for anyone living outside the euro area.",
      sectionStoricoTitle: "📚 History",
      sectionStoricoText: "Every time a new week starts, the previous one is automatically archived here: you can look back at what you ate, memory photos included, up to 26 weeks back.",
      sectionCalorieTitle: "🔥 Calories",
      sectionCalorieText: "An optional section: it stays hidden until you choose to turn it on. Once on, it shows a calorie summary of your menu and lets you set a daily goal. You can turn it off again at any time.",
      sectionDatiTitle: "🔒 Your data",
      sectionDatiText: "Everything you enter — menu, favourite recipes, photos, expenses, history — stays saved only on your phone or computer, in the browser you're using. There's no account, no sign-up, and no data ever leaves your device. The trade-off: if you switch browser or device, or clear your browsing data, you'll also lose what's saved here.",
      sectionLinguaTitle: "🌐 Language",
      sectionLinguaText: "You can switch the interface language to Italian, English or Spanish using the flags in the top right of every page. Recipes and traditional dishes stay in Italian, but the rest of the app is translated.",
      sectionDisclaimerTitle: "⚠️ Allergy and health disclaimer",
      sectionDisclaimerText: "The information about ingredients, allergens and calories in the app is provided for informational purposes only and is based on the ingredients listed in each recipe, which may be incomplete, inaccurate, or may not account for cross-contamination during preparation. The app does not provide medical, nutritional, or dietary advice of any kind. If you have allergies, intolerances, or other health conditions, always personally check the actual ingredients of the products you buy and consult a doctor or specialist if in doubt. Use of the allergen filters is at your own risk and should not be considered a guarantee of food safety."
    }
  },

  es: {
    nav: { home: "Inicio", menu: "Menú", ricette: "Recetas", scopri: "Descubre", spesa: "Compra", storico: "Historial", calorie: "Calorías", guida: "Guía" },
    common: {
      footerNote: "Tus datos se guardan solo en este dispositivo/navegador.",
      resetAll: "Borrar todos los datos",
      add: "+ Añadir",
      clear: "Borrar"
    },
    days: {
      lunedi: "Lunes", martedi: "Martes", mercoledi: "Miércoles",
      giovedi: "Jueves", venerdi: "Viernes", sabato: "Sábado", domenica: "Domingo"
    },
    meals: { colazione: "Desayuno", pranzo: "Comida", cena: "Cena", spuntini: "Snacks" },
    categorie: { colazione: "Desayuno", pranzo: "Comida", cena: "Cena", spuntino: "Snack" },
    stili: { leggero: "Ligero", bilanciato: "Equilibrado", goloso: "Goloso" },
    tempi: { veloce: "Rápida", elaborato: "Más elaborada" },
    budgetCategorie: { cibo: "Compra de comida", altri: "Otros artículos", consegna: "Comida a domicilio", fuori: "Cenas fuera" },
    allergeni: { glutine: "Gluten", lattosio: "Lactosa", frutta_guscio: "Frutos secos", uova: "Huevos" },
    home: {
      title: "Sfamati",
      subtitle: "Tu kit de supervivencia para la vida Erasmus: qué comer, qué comprar y cuánto gastas, todo en un solo lugar",
      howItWorks: "Por qué esta app",
      intro1: "Sfamati nace por una razón simple: quitarte el esfuerzo de decidir cada día qué comer, qué comprar y cuánto estás gastando, justo en el momento en que ya tienes otras cien cosas nuevas en las que pensar.",
      intro2: "Recetas listas, lista de la compra automática, presupuesto bajo control, platos típicos por descubrir, división de gastos con compañeros de piso y un historial de lo que has comido: todo gratis, sin cuenta y sin publicidad.",
      intro3: "Tus datos se quedan solo en tu dispositivo: no se requiere registro.",
      guidaCta: "📖 Guía completa de todas las funciones",
      dishOfDay: "🍽️ Plato recomendado de hoy",
      navMenuTitle: "Menú Semanal",
      navMenuDesc: "Elige qué comer cada día, entre recetas listas y alimentos libres",
      navRicetteTitle: "Recetas",
      navRicetteDesc: "Más de 1900 platos fáciles, con filtros de pescado, estilo y tiempo de preparación",
      navScopriTitle: "Descubre",
      navScopriDesc: "Los platos típicos del país donde vives tu Erasmus, para probar la cultura local",
      navSpesaTitle: "Lista de la Compra",
      navSpesaDesc: "Generada a partir de tu menú, con presupuesto semanal o mensual, división de gastos con compañeros de piso y gráfico de gastos",
      navCalorieTitle: "Calorías",
      navCalorieDesc: "Opcional: un resumen solo para quien decide activarlo",
      navStoricoTitle: "Historial",
      navStoricoDesc: "Revisa lo que comiste en las semanas anteriores",
      addToMenu: "Añádelo a tu menú",
      statsTitle: "📊 Tus estadísticas",
      statsEmpty: "Empieza a usar la app — menú, recetas, compra — y aquí verás un resumen de lo que has hecho.",
      statsUniqueRecipes: "recetas diferentes probadas",
      statsFavorites: "recetas favoritas",
      statsWeeks: "semanas registradas",
      statsPhotos: "fotos recuerdo",
      statsDeliveries: "pedidos a domicilio",
      statsEatingOut: "cenas fuera",
      statsTotalSpent: "gasto total",
      statsTopDish: "Tu plato más cocinado:",
      statsTopStyle: "Tu estilo favorito:"
    },
    menu: {
      title: "Mi Menú Semanal",
      subtitle: "Elige qué comer día a día, entre recetas listas y alimentos libres",
      viewHistory: "📚 Ver semanas anteriores",
      autoGenerateSummary: "🎲 Generar menú automático",
      autoGenNoFish: "Excluir platos a base de pescado",
      autoGenQuick: "Solo recetas rápidas",
      autoGenOverwrite: "Sustituir también las comidas ya añadidas",
      autoGenAllergeniLabel: "Excluir si eres alérgico/intolerante a:",
      autoGenEvitaLabel: "Otros alimentos a evitar",
      autoGenEvitaPlaceholder: "Ej. champiñones, aceitunas, picante... (separados por comas)",
      autoGenModalitaLabel: "Modo",
      modeMisto: "🎯 Mixto (equilibrado)",
      modeFitness: "💪 Fitness (ligero, menos calorías)",
      modeVeloce: "⚡ Rápido (solo recetas rápidas)",
      modeGoloso: "🍰 Goloso (comfort food)",
      autoGenerateBtn: "Generar el menú de la semana",
      autoGenerateDone: "✅ ¡Hecho! {n} comidas añadidas.",
      autoGenerateNothing: "No se ha añadido ninguna comida: prueba a quitar algún filtro o activa la sustitución.",
      fixedMealsSummary: "📌 Comidas fijas para toda la semana",
      fixedMealsIntro: "Si siempre comes lo mismo en el desayuno (u otra comida), fíjalo aquí una sola vez: se aplica automáticamente a los 7 días, y seguirá haciéndolo también en las próximas semanas hasta que lo cambies o lo quites. Siempre puedes modificar un día concreto sin afectar a los demás, y la generación automática no toca las comidas fijadas.",
      fixedMealsRecipeLabel: "Busca una receta",
      fixedMealsFoodAlt: "O un alimento libre",
      fixedMealsFixBtn: "📌 Fijar para toda la semana",
      fixedMealsRemoveBtn: "✕ Quitar",
      fixedMealsCurrent: "Fijado: {nome}",
      fixedMealsNone: "No fijado"
    },
    ricette: {
      title: "Recetas Recomendadas",
      subtitle: "Más de 1900 platos fáciles para la vida Erasmus, entre carne, pescado y opciones vegetarianas",
      searchPlaceholder: "🔍 Busca una receta por nombre o ingrediente...",
      filterAll: "Todas",
      filterAllStyles: "Todos los estilos",
      filterAllTimes: "Todas las recetas",
      filterElaborate: "Más elaboradas",
      filterFishAll: "🐟 Pescado: todas",
      filterFishExclude: "Excluir pescado",
      filterFishOnly: "Solo pescado",
      allergeneLabel: "Excluir si eres alérgico/intolerante a:",
      allergeneDisclaimer: "⚠️ Atención: este filtro es puramente orientativo y se basa solo en los ingredientes indicados en la receta, que podrían estar incompletos o no reflejar posibles contaminaciones cruzadas. La app no ofrece asesoramiento médico: si tienes una alergia o intolerancia, comprueba siempre los ingredientes reales antes de comer y consulta a un médico en caso de duda.",
      frigoSummary: "🧊 ¿Qué tienes en la nevera? Encuentra recetas con lo que ya tienes",
      frigoPlaceholder: "Ej. calabacín, huevos, tomates... (separados por comas)",
      frigoFind: "Buscar recetas",
      loadMore: "Ver más recetas",
      filterFavorites: "⭐ Solo favoritas",
      filterQuickMode: "⚡ Con prisa"
    },
    scopri: {
      title: "Descubre los Platos Típicos",
      subtitle: "Qué se come en tu ciudad Erasmus (o en la de tus sueños)",
      searchPlaceholder: "🔍 Busca un plato o un país...",
      filterAll: "🌍 Todos los países"
    },
    spesa: {
      title: "Lista de la Compra",
      subtitle: "Generada automáticamente a partir de tu menú semanal",
      refresh: "Actualizar desde el menú",
      clearChecked: "Desmarcar todo",
      fromMenu: "De tu menú semanal",
      emptyShopping: "Todavía no has seleccionado recetas o alimentos en el Menú Semanal.",
      otherItems: "Otros artículos",
      extraNamePlaceholder: "Ej. detergente, papel higiénico...",
      extraQtyPlaceholder: "Cantidad (opcional)",
      budgetTitle: "💶 Presupuesto de comida",
      thisWeek: "Esta semana",
      thisMonth: "Este mes",
      totalSpent: "Total gastado",
      amountPlaceholder: "Importe €",
      notePlaceholder: "Nota (ej. supermercado)",
      shared: "Gasto compartido con los compañeros de piso",
      registerExpense: "+ Registrar gasto",
      roommatesTitle: "👥 Compañeros de piso",
      roommatesHint: "Añade a quienes viven contigo para dividir los gastos compartidos de forma justa.",
      roommateNamePlaceholder: "Nombre del compañero",
      settlementTitle: "🤝 Quién debe qué",
      settlementHint: "Calculado a partir de los gastos compartidos registrados en el periodo seleccionado arriba (semana o mes).",
      currencyTitle: "💱 Conversor de Moneda",
      currencyHint: "Configura tu moneda local y el tipo de cambio para convertir importes al instante.",
      currencyRateLabel: "1 € =",
      currencyRefresh: "Actualizar tipo",
      currencyUpdating: "Actualizando...",
      currencyUpdated: "Tipo actualizado.",
      currencyUpdateFailed: "No se ha podido actualizar automáticamente: usa el tipo manual."
    },
    storico: {
      title: "Historial Semanal",
      subtitle: "Revisa lo que comiste en las semanas anteriores",
      empty: "Todavía no hay semanas archivadas: aparecerán aquí en cuanto empiece una nueva semana en el Menú.",
      noFood: "Ningún alimento añadido.",
      delivery: "a domicilio",
      eatingOut: "fuera de casa"
    },
    calorie: {
      title: "Resumen de Calorías",
      subtitle: "Una sección opcional: solo la ves si decides activarla",
      consentTitle: "¿Quieres llevar un registro de las calorías?",
      consentText: "Es una función opcional. Algunas personas la encuentran útil, otras prefieren no pensar en los números: ambas opciones están bien.",
      consentYes: "Sí, muéstrame el resumen",
      consentNo: "No, prefiero que no",
      declinedTitle: "Aquí no hay números que ver",
      declinedText: "Has elegido no llevar un registro de las calorías. Puedes cambiar de opinión en cualquier momento.",
      changeMind: "Cambiar preferencia",
      dailyGoal: "Objetivo diario",
      hideAgain: "Ocultar de nuevo esta sección"
    },
    guida: {
      title: "Guía de Sfamati",
      subtitle: "Todo lo que necesitas saber para sacarle el máximo partido a la app",
      backHome: "← Volver al Inicio",
      sectionMenuTitle: "📅 Menú Semanal",
      sectionMenuText: "Para cada día elige qué comer en el desayuno, la comida, la cena y los snacks: busca entre las recetas listas o añade un alimento libre escribiéndolo a mano. Si has salido a cenar fuera o has pedido comida a domicilio, regístralo con los botones correspondientes para que también se cuente en el presupuesto. Con \"Generar menú automático\" rellenas toda la semana en un clic, eligiendo entre el modo Mixto, Fitness (ligero, menos calorías), Rápido (solo recetas rápidas) o Goloso (comfort food), excluyendo el pescado y tus alergias/intolerancias (gluten, lactosa, frutos secos, huevos), o cualquier otro alimento que quieras evitar.",
      sectionRicetteTitle: "🍝 Recetas",
      sectionRicetteText: "Más de 1900 recetas filtrables por categoría, estilo (ligero, equilibrado, goloso), tiempo de preparación, presencia de pescado y alérgenos a excluir. Guarda tus favoritas con la estrella, activa el modo \"Con prisa\" para ver solo recetas rápidas con pocos ingredientes, o escribe qué tienes en la nevera para encontrar recetas con lo que ya tienes en casa.",
      sectionScopriTitle: "🌍 Descubre",
      sectionScopriText: "Una colección de platos típicos de 15 países europeos, para probar la cultura local del lugar donde vives tu Erasmus, o solo por curiosidad. Filtra por país o busca un plato concreto.",
      sectionSpesaTitle: "🛒 Lista de la Compra",
      sectionSpesaText: "Se genera automáticamente a partir de los ingredientes de tu Menú Semanal: marca lo que ya has comprado y añade artículos extra no alimentarios. En la misma página encontrarás también el presupuesto (compra, comida a domicilio, cenas fuera) dividido por semana o mes, la división de gastos compartidos con los compañeros de piso y un conversor de moneda para quien vive fuera de la zona euro.",
      sectionStoricoTitle: "📚 Historial",
      sectionStoricoText: "Cada vez que empieza una nueva semana, la anterior se archiva automáticamente aquí: puedes revisar lo que comiste, con fotos recuerdo incluidas, hasta 26 semanas atrás.",
      sectionCalorieTitle: "🔥 Calorías",
      sectionCalorieText: "Una sección opcional: permanece oculta hasta que decides activarla. Si la activas, muestra un resumen de las calorías de tu menú y te permite fijar un objetivo diario. Puedes desactivarla en cualquier momento.",
      sectionDatiTitle: "🔒 Tus datos",
      sectionDatiText: "Todo lo que introduces — menú, recetas favoritas, fotos, gastos, historial — se guarda solo en tu teléfono u ordenador, en el navegador que estás usando. No hay cuenta, ni registro, ni ningún dato que salga de tu dispositivo. La contrapartida: si cambias de navegador o dispositivo, o borras los datos de navegación, también pierdes lo que tienes guardado aquí.",
      sectionLinguaTitle: "🌐 Idioma",
      sectionLinguaText: "Puedes cambiar el idioma de la interfaz a italiano, inglés o español con las banderas en la parte superior derecha de cada página. Las recetas y los platos típicos se mantienen en italiano, pero el resto de la app se traduce.",
      sectionDisclaimerTitle: "⚠️ Aviso sobre alergias y salud",
      sectionDisclaimerText: "La información sobre ingredientes, alérgenos y calorías de la app se ofrece únicamente con fines informativos y se basa en los ingredientes indicados en cada receta, que podrían estar incompletos, ser imprecisos o no tener en cuenta posibles contaminaciones cruzadas durante la preparación. La app no ofrece asesoramiento médico, nutricional ni dietético de ningún tipo. Si sufres alergias, intolerancias u otras condiciones de salud, comprueba siempre personalmente los ingredientes reales de los productos que compras y consulta a un médico o especialista en caso de duda. El uso de los filtros de alérgenos es bajo tu propia responsabilidad y no debe considerarse una garantía de seguridad alimentaria."
    }
  }
};

function getLang() {
  const stored = localStorage.getItem(LANG_KEY);
  return SUPPORTED_LANGS.includes(stored) ? stored : "it";
}

function setLang(lang) {
  if (!SUPPORTED_LANGS.includes(lang)) return;
  localStorage.setItem(LANG_KEY, lang);
  location.reload();
}

function t(path) {
  const lang = getLang();
  const value = resolvePath(I18N[lang], path);
  if (value !== undefined) return value;
  const fallback = resolvePath(I18N.it, path);
  return fallback !== undefined ? fallback : path;
}

function resolvePath(obj, path) {
  return path.split(".").reduce((acc, key) => (acc && acc[key] !== undefined ? acc[key] : undefined), obj);
}

/* Helper per le etichette usate nel rendering dinamico (giorni, pasti, categorie, stile, tempo, budget, allergeni) */
function dayLabel(day) { return t("days." + day); }
function mealLabel(meal) { return t("meals." + meal); }
function categoriaLabel(cat) { return t("categorie." + cat); }
function stileLabel(stile) { return t("stili." + stile); }
function tempoLabel(tempo) { return t("tempi." + tempo); }
function budgetCategoriaLabel(cat) { return t("budgetCategorie." + cat); }
function allergeneLabel(chiave) { return t("allergeni." + chiave); }

function applyI18n() {
  document.querySelectorAll("[data-i18n]").forEach(el => {
    el.textContent = t(el.dataset.i18n);
  });
  document.querySelectorAll("[data-i18n-placeholder]").forEach(el => {
    el.setAttribute("placeholder", t(el.dataset.i18nPlaceholder));
  });
  document.documentElement.lang = getLang();
}

function buildLangSwitcher() {
  const header = document.querySelector(".app-header");
  if (!header || header.querySelector(".lang-switcher")) return;

  const currentLang = getLang();
  const flags = { it: "🇮🇹", en: "🇬🇧", es: "🇪🇸" };

  const wrap = document.createElement("div");
  wrap.className = "lang-switcher";
  wrap.setAttribute("role", "group");
  wrap.setAttribute("aria-label", "Lingua / Language / Idioma");

  SUPPORTED_LANGS.forEach(lang => {
    const btn = document.createElement("button");
    btn.type = "button";
    btn.className = "lang-switcher-btn" + (lang === currentLang ? " active" : "");
    btn.textContent = flags[lang];
    btn.setAttribute("aria-label", lang.toUpperCase());
    btn.addEventListener("click", () => setLang(lang));
    wrap.appendChild(btn);
  });

  header.appendChild(wrap);
}

document.addEventListener("DOMContentLoaded", () => {
  applyI18n();
  buildLangSwitcher();
});
